CLASS LHC_ZR_BMIT_TB_LOG_RAP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZR_BMIT_TB_LOG_RAP
        RESULT result.
ENDCLASS.

CLASS LHC_ZR_BMIT_TB_LOG_RAP IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
